[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4", "pybind11>=2.6", "cmake"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/jax_limbdark/jax_limbdark_version.py"
